name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint || echo "Lint warnings detected, but continuing deployment..."

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      # Cargamos los secrets como variables de entorno
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: dist/

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          # Aquí asumes que el host usa ssh-ed25519, ajusta si fuera rsa o ecdsa
          # y pega la huella que obtuviste con ssh-keyscan, manteniendo ${EC2_HOST} en lugar de la IP
          echo "${EC2_HOST} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJiAdc5WldVUrQtnwONSgzLpVcIdy9U9V1D5ekSCmeFc" >> ~/.ssh/known_hosts

      - name: Create SSH key
        run: |
          echo "${EC2_SSH_KEY}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Copy files to EC2
        run: |
          scp -i deploy_key.pem -r dist ubuntu@${EC2_HOST}:/home/ubuntu/

      - name: Deploy to EC2
        run: |
          ssh -i deploy_key.pem ubuntu@${EC2_HOST} << 'EOF'
            sudo mkdir -p /home/ubuntu/temp-dist
            sudo rm -rf /var/www/html/*
            sudo mv /home/ubuntu/dist/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo systemctl restart nginx
          EOF
